### ISSUE TITLE
Maputnik redux refactor

### ISSUE THREAD

**Issue by justenPalmer** [maplibre/maputnik#272]
I just wanted to get discussion started around a possible Maputnik refactor. I've been looking into ways to organize the business logic of Maputnik and I think Redux may be a good fit. With this refactor would come expression syntax and multi-style support. Along with an interface UX and UI facelift. I wanted to open this up to the Maputnik community for feedback. How do you guys feel about this?

**Comment by orangemug** [comment]
Hi @justenPalmer it's actually pretty close to redux already. There is a single source of truth the style being edited, so uni directional data flow. What missing are the 'actions' currently this is propagated up through each view, which I also think is a bit nasty. I also went through the same thinking when I started contributing.

The reason I've not tackled this so far is that although it's a little hard to read, there is currently little reason to touch that part of the codebase thus far.

Here are some code snippets to help explain how is currently works

https://github.com/maputnik/editor/blob/d6ce13c35632f3848efa78b53a70d9a30ea2a213/src/components/App.jsx#L114-L139

https://github.com/maputnik/editor/blob/d6ce13c35632f3848efa78b53a70d9a30ea2a213/src/components/App.jsx#L161-L167

https://github.com/maputnik/editor/blob/d6ce13c35632f3848efa78b53a70d9a30ea2a213/src/components/layers/LayerEditor.jsx#L100-L102

You'll also need to consider the multiple ways a style gets loaded socket API, localstorage and url. As well as revision history.

https://github.com/maputnik/editor/blob/d6ce13c35632f3848efa78b53a70d9a30ea2a213/src/components/App.jsx#L42-L77

I suggest doing some research and see how the above a flux implementation would fit 

<hr>

I don't believe these tickets are related to this ticket

 - With this refactor would come expression syntax and multi-style support
    - @gregorywolanski is looking at this in #50 
 - Along with an interface UX and UI facelift

**Comment by orangemug** [comment]
From issue #369 

> This could be created as a third party library, one could integrate on top of mapboxgl or openlayers. So it could be totally agnostic of mapping library and even react in a larger sense.
In orther words, we would only be maintaing the state of the map style.

I believe this is how it currently works. There is a single source of truth (the map style) and everything renders from that. The renderers (MapboxGL/OpenLayers) are just components that accept a map style to render. The current renderer is also stored in the map style metadata, see 

https://github.com/maputnik/editor/blob/98c235bc21e7a80c442312ff6464918aaa290ad0/src/components/App.jsx#L420-L432
