### ISSUE TITLE
Provide docker images for releases on dockerhub

### ISSUE THREAD

**Issue by pathmapper** [maplibre/maputnik#489]
Currently, there are no docker images tagged with release numbers on dockerhub:
https://hub.docker.com/r/maputnik/editor/builds

This could lead to confusion, like in https://github.com/maputnik/editor/issues/487.

Also it would be useful to have tagged release images available.

**Comment by pathmapper** [comment]
@orangemug do you have access to the docker hub account?

**Comment by orangemug** [comment]
@pathmapper no I don't. Pinging @lukasmartinelli

**Comment by pathmapper** [comment]
@lukasmartinelli any update here?

**Comment by pathmapper** [comment]
From https://github.com/maputnik/editor/issues/679#issuecomment-622979681:

> since we haven't got access to the dockerhub account we can just publish to GitHub packages instead

**Comment by orangemug** [comment]
So we publish docker images from master now, I guess we should also publish tags.

One thing to note is that you need to login to github docker pre-pull, which is a bit of a PITA

```bash
docker login docker.pkg.github.com --username $GH_USERNAME
```

Maybe we should think again about pushing to [docker hub](https://hub.docker.com/r/maputnik/editor) thoughts?

**Comment by zstadler** [comment]
The maputnik repository on Docker Hub is owned by [maputnik](https://hub.docker.com/u/maputnik) which is a "community organization".
It is possible to [add members to the owners team of an organization](https://hub.docker.com/support/doc/how-do-i-add-a-member-to-the-owners-team-of-an-organization-on-the-docker-hub) on Docker Hub.

@orangemug and @pathmapper,
Could see if maputnik appears on [your list of Docker Hub organizations](https://hub.docker.com/orgs)?

If not, I suggest you [contact Docker Hub support](https://hub.docker.com/support/contact/), describe the situation and ask them to add you as "members of the owners team of maputnik" on Docker Hub.

If needed, Docker Hub support team can verify your "member of Maputnik" status on Github's [maputnik contributors page](https://github.com/maputnik/editor/graphs/contributors):

<img width="50%" src="https://user-images.githubusercontent.com/1304610/83429363-9d2a2780-a43c-11ea-8efa-4a8333ab6cc0.png"/><img width="50%" src="https://user-images.githubusercontent.com/1304610/83429423-b632d880-a43c-11ea-99ce-9c94fa1a9a85.png"/>

**Comment by orangemug** [comment]
Thanks @zstadler. I didn't realise it worked like that, I'll take a look tomorrow around the docker hub UI

**Comment by orangemug** [comment]
@zstadler no access unfortunately.

@lukasmartinelli could `orangemug` to the maputnik org?

**Comment by pathmapper** [comment]
> you need to login to github docker pre-pull, which is a bit of a PITA

Oh, that's surprising and unusable like this, here is the thread:
https://github.community/t/docker-pull-from-public-github-package-registry-fail-with-no-basic-auth-credentials-error/16358

Yep, let's try to get it done with docker hub.

Thanks @zstadler, I'm also having no access there. I've contacted the docker support as suggested. If they add me to the members of the owners team of maputnik, I should be also able to add @orangemug then.

**Comment by zstadler** [comment]
@pathmapper and @orangemug 

I'd like to repeat my suggestion that you [use this page](https://hub.docker.com/support/contact/) to contact Docker Hub support **directly**, describe the situation and ask them to add both of you as "members of the owners team of maputnik" on Docker Hub.

**Comment by pathmapper** [comment]
@zstadler I've already contacted the Docker Hub support directly using the form on that page on June 4th, see https://github.com/maputnik/editor/issues/489#issuecomment-638775446:

>  I've contacted the docker support as suggested. 



Until now I've only got an automatic response which says:

> Your request has been received and is being reviewed by our support staff.

**Comment by zstadler** [comment]
@pathmapper, I've missed that statement, sorry.

**Comment by pathmapper** [comment]
No worries @zstadler, I'll keep you updated if there is any response from the Docker Hub support.

**Comment by pathmapper** [comment]
Just a short update:

I've contacted the Docker support on June, 30th regarding the status of my original request (June, 4th). But until now there's no response. Just sent another email to them.

So there's no reaction from Docker support since more then 6 weeks. We should again try to find one of the current members of the owners team of Maputnik at Dockerhub and ask to add @orangemug and/or @pathmapper .

@lukasmartinelli @klokan do you have access to https://hub.docker.com/u/maputnik?

**Comment by lukasmartinelli** [comment]
@orangemug I added you.

![image](https://user-images.githubusercontent.com/1288339/88103453-e30a8e80-cb55-11ea-8300-59336752ecaf.png)

**Comment by lukasmartinelli** [comment]
![image](https://user-images.githubusercontent.com/1288339/88103547-03d2e400-cb56-11ea-8559-869c11490fde.png)
@pathmapper what's your username on DockerHub?

**Comment by pathmapper** [comment]
> @pathmapper what's your username on DockerHub?

It's "pathmapper", thanks a lot @lukasmartinelli !

**Comment by pathmapper** [comment]
I've deleted not needed tags from DockerHub and manually uploaded images for the last three releases:
https://hub.docker.com/r/maputnik/editor/tags

@orangemug I think you should have the permissions to set up automated builds for release tags:
https://docs.docker.com/docker-hub/builds/link-source/
https://hub.docker.com/repository/docker/maputnik/editor/builds/edit

**Comment by zstadler** [comment]
Thank you @lukasmartinelli !

**Comment by orangemug** [comment]
Thanks @lukasmartinelli

**Comment by zstadler** [comment]
@orangemug, @pathmapper 
Isn't this issue resolved already?

**Comment by pathmapper** [comment]
> Isn't this issue resolved already?

@zstadler for the current releases, yes. But we should set up automated builds for release tags so we don't have to upload them manually all the time.

**Comment by zstadler** [comment]
@pathmapper, 

Perhaps these could help:

https://docs.docker.com/ci-cd/github-actions/

https://dev.to/ivandotv/automate-publishing-of-your-github-repository-to-docker-hub-5872

**Comment by HarelM** [comment]
Docker image is now published to github container repository (ghcr), not sure it's worth the trouble of contacting dockerhub.
It is also in the readme of the repo so people can use the image.
Feel free to open a new issue if this is still a problem.
