### ISSUE TITLE
Option to post style to an external api

### ISSUE THREAD

**Issue by nextstopsun** [maplibre/maputnik#592]
I'd be great to have an option to post current style to an external api. (it can be a storage or a processing api, whatever). 
Just an option to set a url of external api and do a POST request, which sends current style json to that url.
This could be added to an `Export` window.

**Comment by HarelM** [comment]
A post request might require authentication, headers and other things that might be hard to configure as a wise range support.
I think exporting the file and uploading it to where you want to store it is a good solution.
Closing for now, if this still feels like a feature you would like to support please open a new ticket with more solutions to headers, cookies etc.
