### ISSUE TITLE
v1.8.0 release

### ISSUE THREAD

**Issue by orangemug** [maplibre/maputnik#665]
Now that we've got v1.7.0 release (again well done everyone) lets start planning v1.8.0, I've put a few issues in the [v1.8.0 milestone](https://github.com/maputnik/editor/milestone/6) of stuff I think we should concentrate on.

I'd like the next release (and future releases) to be a smaller. So I purpose we have a 1 or 2 major things that we shoot for and a bunch of smaller bugs. So in the next release I'm suggesting that we concentrate on

 - Accessibility - I've bundling a couple of ticket into a larger piece of work [accessibility tickets](https://github.com/maputnik/editor/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility) 
 - Advanced expression editor - https://github.com/maputnik/editor/issues/622

The reason for doing 'feature' releases, is so we can communicate better our changes to the editor in the release blog post https://maputnik.github.io/blog/2020/04/23/release-v1.7.0

Note that I'll still fix any serious bugs in a hotfix release, which wouldn't contain the new v1.8.0 changes.

Thoughts?

**Comment by pathmapper** [comment]
@orangemug I also think it's better doing smaller releases more often for various reasons, e.g. also for having a more up-to-date version on https://maputnik.github.io/editor.

Good choice of issues for the `v1.8.0` milestone :+1: 

If we are doing releases more often from now on, maybe adding also one or two of the open tickets / ideas which are related to our workflow to save some time for things which could be automated?

Mainly automatic Desktop builds come to mind as suggested by @lukaswelte (we still need to publish Desktop builds for `v1.7.0`) but there are others, e.g.:

- Automate deployments (https://github.com/maputnik/editor/issues/173)
- Bot for posting test build link to PR (#456)
- Provide docker images for releases on dockerhub (#489)

**Comment by orangemug** [comment]
@pathmapper yup good idea, I've added those issues to the milestone.

**Comment by HarelM** [comment]
Closing this for now as version 1.8 was never released.
I hope more people will start to contribute and I hope those will drive innovation of maputnik according to what people need (this is probably naive of me, but what do I have to loose?).
