### ISSUE TITLE
Add a code of conduct

### ISSUE THREAD

**Issue by orangemug** [maplibre/maputnik#702]
We should add a code of conduct, to be welcoming to everybody who wishes to participate in the project.

@pathmapper are you happy with us adding <https://www.contributor-covenant.org/version/2/0/code_of_conduct/>, it's suggested in the GitHub guidelines.

I'll finally get around to fixing my `@orangemug.co.uk` email address. It currently just bounces (yeah... don't ask) and I'll add that as the email. It'd also be good to add your email (@pathmapper) if you're ok with that.

**Comment by pathmapper** [comment]
That's fine @orangemug and I'm ok with adding my email.
I like also your idea creating one single email address (https://github.com/maputnik/editor/issues/700#issuecomment-638037435), so that incoming emails would automatically reach all maintainers.

**Comment by HarelM** [comment]
This was added as part of the migration to Maplibre organization.
