### ISSUE TITLE
Add logfile to keep track of style changes

### ISSUE THREAD

**Issue by kaykasus** [maplibre/maputnik#743]
Is it possible to implement a log file to keep track of changes/improvements inside the maputnik editor? Often other people change stuff inside the editor but it's almost impossible to find out what has changed. Right now I am using a difference checker to check for changes inside the JSON files but that's not optimal.

**Comment by orangemug** [comment]
I'd probably suggest using git/github to track changes and maputnik as the editor. Similar to how a text editor often doesn't display changes diffs. I could imagine this would be a good additional tool, take a git history or github and show smart diffs based on the `@mapbox/mapbox-gl-style-spec`, some example usage in https://github.com/maputnik/editor/blob/51fa4a4377a796106acbee5a815ada03b10ccceb/src/libs/diffmessage.js

**Comment by pathmapper** [comment]
Load/save from/to Github Repo is tracked in https://github.com/maputnik/editor/issues/155 .

Gists are also showing diffs, e.g. https://gist.github.com/pathmapper/6b41e9ab82e2a4aac95b66d8378fa18f/revisions (Gist export is tracked in https://github.com/maputnik/editor/issues/239).

**Comment by HarelM** [comment]
Closing, git is your friend here, undo and redo exist.
