### ISSUE TITLE
Feature request: clustered GeoJson sources

### ISSUE THREAD

**Issue by m0nac0** [maplibre/maputnik#756]
According to the Mapbox style spec, GeoJson sources have a cluster property (https://docs.mapbox.com/mapbox-gl-js/style-spec/sources/#geojson-cluster).

It would be nice if this could be set in Maputnik.

If I manually download the style, add a `"cluster": true` to the GeoJson source and upload it again, it works fine. So it seems that only an additional checkbox to set the cluster attribute when adding a GeoJson source would be required.

**Comment by Eliav-B** [comment]
It's a good idea, I created PR #810  to solve this

**Comment by HarelM** [comment]
Closed by #810
