### ISSUE TITLE
Docker image shows "Invalid host header"

### ISSUE THREAD

**Issue by AnubhutiRoX** [maplibre/maputnik#758]
Similar to issue #301. When I deploy my app in docker from local, I am able to see its up and running on localhost:<port>. When I try to deploy it on kubernetes environment, it returns invalid host header.

I am using React>17 and nx for microfront end.

docker file is - 

# build environment
FROM node:14.18.1-buster-slim
ARG APPNAME

WORKDIR /home/${APPNAME}
COPY package.json package.json

RUN npm install --registry=<private-registry>
RUN npm i -g @nrwl/cli --registry=<private-registry>
COPY . ./
# Building Specific app
RUN echo ${APPNAME}

RUN nx build ${APPNAME}

RUN groupadd -g 10000 10000 && \
useradd -u 10000 -g 10000 -m -d /home/${APPNAME} -s /bin/bash 10000 && \
mkdir -p /opt/dummy/logs && \
chown -R 10000:10000 /opt

EXPOSE 4200

CMD nx serve ${APPNAME} --host=0.0.0.0 --disableHostCheck

**Comment by HarelM** [comment]
I don't think this issue is still relevant.
If it is, please open a new issue.
The current docker image uses nginx so you can update the configuration as needed.
