### ISSUE TITLE
@mapbox_mapbox-gl-style-spec@13.26.0@@mapbox/mapbox-gl-style-spec/deref.js

### ISSUE THREAD

**Issue by HongLingJin1994** [maplibre/maputnik#790]
**Why compile back:**

_"ERROR in ./node_modules/_@mapbox_mapbox-gl-style-spec@13.26.0@@mapbox/mapbox-gl-style-spec/deref.js 5:12
Module parse failed: Unexpected token (5:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import refProperties from './util/ref_properties.js';"_

**What do I need to do?**

**Comment by HarelM** [comment]
This code now doesn't use the mapbox style spec, but instead the maplibre style spec package.
I believe this issue is no longer relevant.
Closing.
If this is still relevant please open a new issue.
