### ISSUE TITLE
Releases?

### ISSUE THREAD

**Issue by immanuel-h** [maplibre/maputnik#802]
Last tagged release was 1.7.0 from 2020. What happened to the plans on 1.8.0 and even 1.9.0 mentioned in #701 ? I see plenty of work happening in the repo, that's why I'm wondering.

Any insights welcome :)

**Comment by HarelM** [comment]
I'll see if I can carve out a release after the migration to typescript, vite, cypress and other dependencies.

**Comment by HarelM** [comment]
A new version is released every merge to main.
Closing this issue.

**Comment by nyurik** [comment]
Note #875 - releases only update the editor hosted on maplibre.org, not the one on maputnik.github.com

**Comment by birkskyum** [comment]
Maybe we don't need this landing page, and the extra deployment of the editor anymore.

**Comment by nyurik** [comment]
That page is well established and gets all the traffic. We should simply update its links,  and also make sure to redirect old editor to the new one

**Comment by birkskyum** [comment]
Fair enough. It would be good to update the mapbox-style-spec to maplibre-style-spec similar to communication in the rest of the project as well.

**Comment by birkskyum** [comment]
![image](https://github.com/maplibre/maputnik/assets/74932975/2d3aae18-4cb7-4978-bb30-a26fde19d323)

**Comment by HarelM** [comment]
Well... I personally don't see any use for this landing page, I also don't have the permission to update it, feel free to push a change there.
Although, technically, the current version there uses mapbox, so it's not wrong 😃

**Comment by birkskyum** [comment]
Continued in
- https://github.com/maputnik/maputnik.github.io/pull/29
