### ISSUE TITLE
Where to see currently available MapLibre GL JS version

### ISSUE THREAD

**Issue by LennardRouteYou** [maplibre/maputnik#827]
Is there a way where I can see which MapLibre GL JS version is currently available in the Maputnik editor? I'm currently trying to use a [layout property added in MapLibre GL JS 3.3.0](https://maplibre.org/maplibre-style-spec/layers/#layout-symbol-text-variable-anchor-offset), but Maputnik doesn't seem to recognize the property yet.

**Comment by zstadler** [comment]
As far as I can tell, it is set here:

https://github.com/maputnik/editor/blob/b7838ad6e112636c23ec79c9ee015feed17f5535/package.json#L51

**Comment by HarelM** [comment]
Current version is in package.json file.
Assuming we'll continue the concept of CI/CD you can safely assume that the latest code in main is deployed and the latest package.json is relevant.
