### ISSUE TITLE
Migration fix-ups in https://maplibre.org/maputnik

### ISSUE THREAD

**Issue by zstadler** [maplibre/maputnik#861]
**Maputnik version**: v2.0.0-pre.2
**Browser**: All
**OS**: All

**Description of the bug**:
Fix some issues related to the migration from https://maputnik.github.io/editor to https://maplibre.org/maputnik

- [ ] Broken icon in top-left corner
   ![image](https://github.com/maplibre/maputnik/assets/1304610/a25cada7-8d6a-4e75-b84c-76460a229656)
- [x] Maputnik link points to https://maputnik.github.io/editor and relies on the redirection
   ![image](https://github.com/maplibre/maputnik/assets/1304610/916509cd-8c83-4df1-aeae-53cafeed7b3f)
- [x] Help link points to https://github.com/maputnik/editor/wiki and relies on the redirection
   ![image](https://github.com/maplibre/maputnik/assets/1304610/5c049ecd-e3fb-4cb6-8cfa-38925326ecef)
- [x] Remove broken survey
   ![image](https://github.com/maplibre/maputnik/assets/1304610/ee00a363-a74b-44a3-aef6-a8bd5c5c7c91)

**Comment by HarelM** [comment]
Any chance you can check which was solved as part of the following PR:
https://github.com/maplibre/maputnik/pull/860
I see that the icon is still an issue, not sure about the rest.

**Comment by zstadler** [comment]
Yes. The missing icon is the only missing part.
