### ISSUE TITLE
Inspect's popup truncates the property values

### ISSUE THREAD

**Issue by zstadler** [maplibre/maputnik#868]
**Maputnik version**: v2.0.0-pre.2
**Browser**: All
**OS**: All

**Description of the bug**:
The Inspect's popup does not show much of the properties values. Instead, there is a large gap between the property name and the value.

**Steps to reproduce the behavior**:
1. Open any style with a vector source, such as the pre-loaded "OSM Liberty" style
2. Change to Inspect view
3. Move the mouse around the map

**Screenshots**:
![image](https://github.com/maplibre/maputnik/assets/1304610/04959a38-b1db-4b13-bffa-439ea42a32c9)

**Comment by HarelM** [comment]
This is probably related to some css issues.
Can you provide a screen shot of the same place in 1.7 (previous maputnik website)?
I also think the is a problem with the modal dialog widths.

**Comment by HarelM** [comment]
I've seen this block stuff in the code, it's very confusing to understand and see where a block wraps another block...
You should be able to workaroud this locally by changing some css class in the browser itself.
Never the less, this needs fixing...

**Comment by zstadler** [comment]
It is not clear to me why `<input ...>` is used for the values column, as values it contains cannot be changed.

This may or may not be causing some small vertical offset between the two columns:

![image](https://github.com/maplibre/maputnik/assets/1304610/dc9159f5-53e2-4638-aace-8c1993278a83)

I believe this pop-up would be better off as simple table with same formatting for both columns, where the tags use just 30% of the width.
