### ISSUE TITLE
add toggle `localIdeographFontFamily` options of MapLibre GL JS for CJK fonts

### ISSUE THREAD

**Issue by Kanahiro** [maplibre/maputnik#892]
https://maplibre.org/maplibre-gl-js/docs/examples/local-ideographs/

- In MapLibre GL JS, if you need to load CJK fonts, you have to set `localIdeographFontFamily`.
- It seems that current version of Maputnik doesn't provide any feature to toggle this option.
- IMHO, it is better to add anything to toggle this options. What do you think?

**Comment by HarelM** [comment]
Is there a default we can use that will "just work" like we do for RTL languages (We always load the RTL plugin)?
I prefer something that the user won't need to configure if possible...

**Comment by HarelM** [comment]
Feel free to open a PR with the relevant change, probably around here:
https://github.com/maplibre/maputnik/blob/ff15b77b7f07e009457198b232e99344f1bc9ce2/src/components/MapMaplibreGl.tsx#L130
I don't have the means to test this, so if you could make sure it works before opening the PR it would be great.
