### ISSUE TITLE
Broken links on the wiki

### ISSUE THREAD

**Issue by joostschouppe** [maplibre/maputnik#894]
On the [wiki](https://github.com/maplibre/maputnik/wiki), [Design a Map Style](https://github.com/maplibre/maputnik/Design-a-Map-Style) and [Add and Style GeoJSON files](https://github.com/maplibre/maputnik/Style-GeoJSON-Files) retun a 404 because the word wiki is missing in the URL

**Comment by HarelM** [comment]
I think I just fixed those, let me know if there are other stuff worth fixing in the wiki.
If not, feel free to close this issue.

**Comment by joostschouppe** [comment]
Thanks for the fix!
I'll keep an eye out and re-open if I spot anything
