### ISSUE TITLE
Styles not loading - self hosted map server

### ISSUE THREAD

**Issue by ajh2oman** [maplibre/maputnik#899]
Hi, I'm trying to edit the map style on my self-hosted server but I can't seem to get the styles to properly load. I have the full planet of OSM loaded on the server but when I try to add any of the gallery styles the map appears blank. OSM Liberty loads the globe but the Natural Earth layer only if that helps point to the problem at all. Zoomstack also works but only for a small part of the world. I assume there is some misconnect between the OSM map file on my server and Maputnik...

![osm liberty](https://github.com/maplibre/maputnik/assets/33510351/95ec6393-41b0-423f-951f-5351278d9a91)

**Comment by HarelM** [comment]
Can you clarify the steps to reproduce the issue? It is not clear from the above report...

**Comment by ajh2oman** [comment]
**Link:** http://89.117.21.238:8888/

**Steps to reproduce**:
Open -> Gallery Styles -> OSM Liberty
Only Natural Earth available
Open -> Gallery Styles -> Positron
Blank Map

I followed instructions on https://openmaptiles.org/docs/style/maputnik/

**Comment by HarelM** [comment]
I would recommend following the wiki for instructions on how to use maputnik, and I would recommend also starting to use it in the online version and not a locally hosted one that probably doesn't have the right CORS permissions and the right key for maptiler tiles...
https://maplibre.org/maputnik/

**Comment by ajh2oman** [comment]
Ok thanks, I'll give that a try

**Comment by HarelM** [comment]
Closing for now, if this is still relevant, please let us know.
