### ISSUE TITLE
Update the Gallery styles (MapTiler Basic, Dark Matter, Position, OSM Bright and Toner) to the latest version

### ISSUE THREAD

**Issue by bolollo** [maplibre/maputnik#901]
Update the Gallery styles (MapTiler Basic, Dark Matter, Position, OSM Bright, and Toner) to the latest version.

The new [version (v3.15) of OpenMapTiles](https://www.maptiler.com/news/2024/04/openstreetmap-data-prepared-for-advanced-cartography/) was released at the end of April, and the styles (MapTiler Basic, Dark Matter, Position, etc.) have also been updated.

The main change in the styles is to use https://api.maptiler.com/tiles/v3-openmaptiles/ as a data source (based exclusively on the schema (https://docs.maptiler.com/schema/omt -planet /) from OpenMapTiles) instead of the data source https://api.maptiler.com/tiles/v3/ a schema (https://docs.maptiler.com/schema/planet/) from MapTiler (based on OpenMapTiles )

**Comment by HarelM** [comment]
Feel free to open a PR. I personally don't have any objections.

**Comment by HarelM** [comment]
Add it to the existing PR.
