### ISSUE TITLE
Button to reset to default layers

### ISSUE THREAD

**Issue by RayBB** [maplibre/maputnik#918]
Hello, it would be nice if there was a way to reset the layers to the default ones without clearing the local cache.
Some of my non-techy friends were putzing around with it and got stuck after deleting one too many layers and couldn't figure out how to get them back.

**Comment by HarelM** [comment]
Doesn't opening a style from the list solves this issue?

**Comment by RayBB** [comment]
Yes it does exactly that. I didn't even realize that was an option because I thought "open" meant like open a file on your computer or something. Now I see how to do it. Thanks!
