### ISSUE TITLE
Compile desktop with the current code

### ISSUE THREAD

**Issue by robnorber** [maplibre/maputnik#919]
The desktop version uses 1.7, and doesn't work for me at all (produces errors). I want to compile it with the current code that's in the main branch. How do I do it?

**Comment by robnorber** [comment]
Is it possible to use the Docker image with a local json?

**Comment by HarelM** [comment]
This was the idea in the past, I don't know if it's possible now without fixing the code. 
If this is your use case you are welcome to try and help 😃
