### ISSUE TITLE
Allow specifying tile size with Raster sources

### ISSUE THREAD

**Issue by louwers** [maplibre/maputnik#946]
Since this is supported by the spec, this should ideally be configurable when creating or modifying a raster tile source.

https://maplibre.org/maplibre-style-spec/sources/#tilesize

**Comment by teyotan** [comment]
May I try to work on this?

**Comment by HarelM** [comment]
Sure, Enjoy!

**Comment by teyotan** [comment]
I think I am done (?)
Not so sure myself hahaha

I don't see other sources fields (like scheme, max zoom, min zoom) referenced on other part of the source code, are they not used in Maputnik?

**Comment by bolollo** [comment]
@HarelM I think this issue can be closed since it is resolved in https://github.com/maplibre/maputnik/pull/947 Thanks
