### ISSUE TITLE
Add OSM OpenMapTiles to style gallery list

### ISSUE THREAD

**Issue by bolollo** [maplibre/maputnik#949]
Add the https://openmaptiles.org/styles/#osm-openmaptiles to the gallery.

This style simulates the traditional OSM style.

I recently saw that a style with an API key is included in the gallery style list, such as https://github.com/maplibre/maputnik/blob/172d4d527872e92f2c522f603ee7378c44488cb1/src/config/styles.json#L77. 

In this case, the OSM OMT style would be loaded from https://api.maptiler.com/maps/openstreetmap/style.json?key=YOUR_MAPTILER_API_KEY_HERE (using the API key we have enabled for MapLibre: https://github.com/maplibre/maputnik/blob/172d4d527872e92f2c522f603ee7378c44488cb1/src/config/tokens.json#L2).

I can prepare the PR, but I have a couple of questions:

Do I put the key hard-coded with the style, or is there another way to do it?

Do I have to upload the thumbnail to https://maputnik.github.io/thumbnails, or can it be an external URL like https://openmaptiles.org/img/styles/openmaptiles.png?

**Comment by roblabs** [comment]
In this case, I recommend submitting a PR with an access token that is restricted to both of the domains `localhost` and `maplibre.org`.  Check with your tile server provider to see if they support *domain restriction* or *domain origin*.

The [current version of Maputnik](https://github.com/maplibre/maputnik/blob/main/src/libs/field-spec-additional.ts) has references on how to do Domain or Origin restriction.  
* https://docs.maptiler.com/cloud/api/authentication-key
* https://www.thunderforest.com/docs/apikeys
* https://docs.stadiamaps.com/authentication
---

The ProtoMaps.io style that you reference looks like it's keyed to work servers that are either `localhost` or `maplibre.org`

* https://api.protomaps.com/styles/v2/light.json?key=d828297496b11844

That is, when I click on the link, the server replies with the following,

> *Invalid origin for API key*

The Protomap Light style works off these servers:
* 🟢 http://localhost:8888
* 🟢 https://maplibre.org/maputnik

but not when I reference the Protomap Light style from either of these cases, it fails.  Which seems to be the intention

* 🔴 http://linuxbox.local:8888   # same Maputnik on the same port, but not `localhost`  
*  🔴 [Maputnik fork](https://doi-nps.github.io/maputnik/)

**Comment by bolollo** [comment]
Thanks @roblabs 

PR done: https://github.com/maplibre/maputnik/pull/956

The API key is restricted to maplibre.org

[https://api.maptiler.com/maps/openstreetmap/style.json?key=get_your_own_OpIi9ZULNHzrESv6T2vL](https://api.maptiler.com/maps/openstreetmap/style.json?key=get_your_own_OpIi9ZULNHzrESv6T2vL)

when I click on the link, the server replies with the following,

```
Key usage restricted - Get your FREE key at https://cloud.maptiler.com/account/keys/
```
